
package com.byzoro.com.guotou.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MTProxyService", targetNamespace = "http://version2.byzoro.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface MTProxyService {


    @WebMethod(operationName = "AlarmInform")
    @WebResult(partName = "return")
    @Action(input = "http://version2.byzoro.com/MTProxyService/AlarmInformRequest", output = "http://version2.byzoro.com/MTProxyService/AlarmInformResponse")
    public String alarmInform(
        @WebParam(name = "cameraID", partName = "cameraID")
        String cameraID,
        @WebParam(name = "fileName", partName = "fileName")
        String fileName,
        @WebParam(name = "alarmType", partName = "alarmType")
        String alarmType,
        @WebParam(name = "alarmTime", partName = "alarmTime")
        String alarmTime,
        @WebParam(name = "alarmPicture", partName = "alarmPicture")
        String alarmPicture,
        @WebParam(name = "alarmVideo", partName = "alarmVideo")
        String alarmVideo);

}
