
package com.byzoro;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UploadFileInterface", targetNamespace = "http://byzoro.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class,
    org.w3._2005._05.xmlmime.ObjectFactory.class
})
public interface UploadFileInterface {


    /**
     *
     * @param alarmType
     * @param cameraID
     * @param fileSources
     * @param alarmTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AlarmInform")
    @WebResult(partName = "return")
    @Action(input = "http://byzoro.com/UploadFileInterface/AlarmInformRequest", output = "http://byzoro.com/UploadFileInterface/AlarmInformResponse")
    public String alarmInform(
            @WebParam(name = "cameraID", partName = "cameraID")
                    String cameraID,
            @WebParam(name = "alarmType", partName = "alarmType")
                    String alarmType,
            @WebParam(name = "alarmTime", partName = "alarmTime")
                    String alarmTime,
            @WebParam(name = "fileSources", partName = "fileSources")
                    FileSources fileSources);

}
